// constants for basic info object
export const LOAD_BROWSER_NAME = 'LOAD_BROWSER_NAME';
export const LOAD_BROWSER_VERSION = 'LOAD_BROWSER_VERSION';

// constants for pages info list object
export const LOAD_PAGES_LIST = 'LOAD_PAGES_LIST';
export const LOAD_SUBSCRIBERS_LIST='LOAD_SUBSCRIBERS_LIST';
export const LOAD_SURVEYS_LIST='LOAD_SURVEYS_LIST';
export const FETCH_BROADCASTS_LIST = 'FETCH_BROADCASTS_LIST';
export const ADD_BROADCAST = 'ADD_BROADCAST';
export const EDIT_BROADCAST = 'EDIT_BROADCAST';
export const FETCH_PAGES_LIST = 'FETCH_PAGES_LIST';
export const LOAD_WORKFLOW_LIST = 'LOAD_WORKFLOW_LIST';
export const ADD_WORKFLOW = 'ADD_WORKFLOW';
export const FETCH_POLLS_LIST = 'FETCH_POLLS_LIST';
export const ADD_POLL = 'ADD_POLL';
export const GET_BROADCAST='GET_BROADCAST';
export const ADD_SURVEY='ADD_SURVEY';
export const ADD_RESPONSES='ADD_RESPONSES';
export const ADD_POLL_RESPONSES='ADD_POLL_RESPONSES';
export const LOAD_USER_DETAILS='LOAD_USER_DETAILS';
export const SEND_POLL='SEND_POLL';
export const LOAD_SURVEYS_QUESTIONS='LOAD_SURVEYS_QUESTIONS';