/* eslint-disable no-unused-vars */
/**
 * Created by sojharo on 11/01/2018.
 */

let simpleText = {
  'created_at': 'Thu Jan 11 17:30:59 +0000 2018',
  'id': 951506738586505200,
  'id_str': '951506738586505216',
  'text': '#kibopush is doing great job.',
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'truncated': false,
  'in_reply_to_status_id': null,
  'in_reply_to_status_id_str': null,
  'in_reply_to_user_id': null,
  'in_reply_to_user_id_str': null,
  'in_reply_to_screen_name': null,
  'user': {
    'id': 2616186000,
    'id_str': '2616186000',
    'name': 'Sojharo',
    'screen_name': 'SojharoMangi',
    'location': 'Hyderabad, Sindh',
    'url': null,
    'description': 'Enthusiastic about #WebRTC, #WebApp, #ECommerce, #ArtificialIntelligence, #MEAN, #Reading, #Writing, #Programming, #Philosophy http://lnkd.in/qCKxwr',
    'translator_type': 'none',
    'protected': false,
    'verified': false,
    'followers_count': 90,
    'friends_count': 98,
    'listed_count': 10,
    'favourites_count': 26,
    'statuses_count': 77,
    'created_at': 'Thu Jul 10 21:45:54 +0000 2014',
    'utc_offset': 18000,
    'time_zone': 'Asia/Karachi',
    'geo_enabled': false,
    'lang': 'en',
    'contributors_enabled': false,
    'is_translator': false,
    'profile_background_color': 'C0DEED',
    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_tile': false,
    'profile_link_color': '1DA1F2',
    'profile_sidebar_border_color': 'C0DEED',
    'profile_sidebar_fill_color': 'DDEEF6',
    'profile_text_color': '333333',
    'profile_use_background_image': true,
    'profile_image_url': 'http://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2616186000/1405029950',
    'default_profile': true,
    'default_profile_image': false,
    'following': null,
    'follow_request_sent': null,
    'notifications': null
  },
  'geo': null,
  'coordinates': null,
  'place': null,
  'contributors': null,
  'is_quote_status': false,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {
    'hashtags': [{'text': 'kibopush', 'indices': [0, 9]}],
    'urls': [],
    'user_mentions': [],
    'symbols': []
  },
  'favorited': false,
  'retweeted': false,
  'filter_level': 'low',
  'lang': 'en',
  'timestamp_ms': '1515691859276'
}

let simpleTweetWithURLandText = {
  'created_at': 'Thu Jan 11 17:33:28 +0000 2018',
  'id': 951507363831451600,
  'id_str': '951507363831451649',
  'text': '#kibopush is going live https://t.co/Hn40MJkKho',
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'truncated': false,
  'in_reply_to_status_id': null,
  'in_reply_to_status_id_str': null,
  'in_reply_to_user_id': null,
  'in_reply_to_user_id_str': null,
  'in_reply_to_screen_name': null,
  'user': {
    'id': 2616186000,
    'id_str': '2616186000',
    'name': 'Sojharo',
    'screen_name': 'SojharoMangi',
    'location': 'Hyderabad, Sindh',
    'url': null,
    'description': 'Enthusiastic about #WebRTC, #WebApp, #ECommerce, #ArtificialIntelligence, #MEAN, #Reading, #Writing, #Programming, #Philosophy http://lnkd.in/qCKxwr',
    'translator_type': 'none',
    'protected': false,
    'verified': false,
    'followers_count': 90,
    'friends_count': 98,
    'listed_count': 10,
    'favourites_count': 26,
    'statuses_count': 78,
    'created_at': 'Thu Jul 10 21:45:54 +0000 2014',
    'utc_offset': 18000,
    'time_zone': 'Asia/Karachi',
    'geo_enabled': false,
    'lang': 'en',
    'contributors_enabled': false,
    'is_translator': false,
    'profile_background_color': 'C0DEED',
    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_tile': false,
    'profile_link_color': '1DA1F2',
    'profile_sidebar_border_color': 'C0DEED',
    'profile_sidebar_fill_color': 'DDEEF6',
    'profile_text_color': '333333',
    'profile_use_background_image': true,
    'profile_image_url': 'http://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2616186000/1405029950',
    'default_profile': true,
    'default_profile_image': false,
    'following': null,
    'follow_request_sent': null,
    'notifications': null
  },
  'geo': null,
  'coordinates': null,
  'place': null,
  'contributors': null,
  'is_quote_status': false,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {
    'hashtags': [{'text': 'kibopush', 'indices': [0, 9]}],
    'urls': [
      {
        'url': 'https://t.co/Hn40MJkKho',
        'expanded_url': 'http://kibopush.com',
        'display_url': 'kibopush.com',
        'indices': [24, 47]
      }],
    'user_mentions': [],
    'symbols': []
  },
  'favorited': false,
  'retweeted': false,
  'possibly_sensitive': false,
  'filter_level': 'low',
  'lang': 'en',
  'timestamp_ms': '1515692008346'
}

let tweetWithURLOnly = {
  'created_at': 'Thu Jan 11 17:53:00 +0000 2018',
  'id': 951512281392865300,
  'id_str': '951512281392865280',
  'text': 'https://t.co/bCJAruQHzE',
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'truncated': false,
  'in_reply_to_status_id': null,
  'in_reply_to_status_id_str': null,
  'in_reply_to_user_id': null,
  'in_reply_to_user_id_str': null,
  'in_reply_to_screen_name': null,
  'user': {
    'id': 2616186000,
    'id_str': '2616186000',
    'name': 'Sojharo',
    'screen_name': 'SojharoMangi',
    'location': 'Hyderabad, Sindh',
    'url': null,
    'description': 'Enthusiastic about #WebRTC, #WebApp, #ECommerce, #ArtificialIntelligence, #MEAN, #Reading, #Writing, #Programming, #Philosophy http://lnkd.in/qCKxwr',
    'translator_type': 'none',
    'protected': false,
    'verified': false,
    'followers_count': 90,
    'friends_count': 98,
    'listed_count': 10,
    'favourites_count': 26,
    'statuses_count': 79,
    'created_at': 'Thu Jul 10 21:45:54 +0000 2014',
    'utc_offset': 18000,
    'time_zone': 'Asia/Karachi',
    'geo_enabled': false,
    'lang': 'en',
    'contributors_enabled': false,
    'is_translator': false,
    'profile_background_color': 'C0DEED',
    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_tile': false,
    'profile_link_color': '1DA1F2',
    'profile_sidebar_border_color': 'C0DEED',
    'profile_sidebar_fill_color': 'DDEEF6',
    'profile_text_color': '333333',
    'profile_use_background_image': true,
    'profile_image_url': 'http://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2616186000/1405029950',
    'default_profile': true,
    'default_profile_image': false,
    'following': null,
    'follow_request_sent': null,
    'notifications': null
  },
  'geo': null,
  'coordinates': null,
  'place': null,
  'contributors': null,
  'is_quote_status': false,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {
    'hashtags': [],
    'urls': [
      {
        'url': 'https://t.co/bCJAruQHzE',
        'expanded_url': 'https://www.yahoo.com',
        'display_url': 'yahoo.com',
        'indices': [0, 23]
      }],
    'user_mentions': [],
    'symbols': []
  },
  'favorited': false,
  'retweeted': false,
  'possibly_sensitive': false,
  'filter_level': 'low',
  'lang': 'und',
  'timestamp_ms': '1515693180784'
}

let tweetwithLinkandTextAndImage = {
  'created_at': 'Thu Jan 11 17:58:37 +0000 2018',
  'id': 951513694952927200,
  'id_str': '951513694952927232',
  'text': 'Link plus image https://t.co/np7vl9fjjd https://t.co/8QXLqcgJjz',
  'display_text_range': [0, 39],
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'truncated': false,
  'in_reply_to_status_id': null,
  'in_reply_to_status_id_str': null,
  'in_reply_to_user_id': null,
  'in_reply_to_user_id_str': null,
  'in_reply_to_screen_name': null,
  'user': {
    'id': 2616186000,
    'id_str': '2616186000',
    'name': 'Sojharo',
    'screen_name': 'SojharoMangi',
    'location': 'Hyderabad, Sindh',
    'url': null,
    'description': 'Enthusiastic about #WebRTC, #WebApp, #ECommerce, #ArtificialIntelligence, #MEAN, #Reading, #Writing, #Programming, #Philosophy http://lnkd.in/qCKxwr',
    'translator_type': 'none',
    'protected': false,
    'verified': false,
    'followers_count': 90,
    'friends_count': 98,
    'listed_count': 10,
    'favourites_count': 26,
    'statuses_count': 79,
    'created_at': 'Thu Jul 10 21:45:54 +0000 2014',
    'utc_offset': 18000,
    'time_zone': 'Asia/Karachi',
    'geo_enabled': false,
    'lang': 'en',
    'contributors_enabled': false,
    'is_translator': false,
    'profile_background_color': 'C0DEED',
    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_tile': false,
    'profile_link_color': '1DA1F2',
    'profile_sidebar_border_color': 'C0DEED',
    'profile_sidebar_fill_color': 'DDEEF6',
    'profile_text_color': '333333',
    'profile_use_background_image': true,
    'profile_image_url': 'http://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2616186000/1405029950',
    'default_profile': true,
    'default_profile_image': false,
    'following': null,
    'follow_request_sent': null,
    'notifications': null
  },
  'geo': null,
  'coordinates': null,
  'place': null,
  'contributors': null,
  'is_quote_status': false,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {
    'hashtags': [],
    'urls': [
      {
        'url': 'https://t.co/np7vl9fjjd',
        'expanded_url': 'https://app.kibopush.com',
        'display_url': 'app.kibopush.com',
        'indices': [16, 39]
      }],
    'user_mentions': [],
    'symbols': [],
    'media': [
      {
        'id': 951513615164674000,
        'id_str': '951513615164674049',
        'indices': [40, 63],
        'media_url': 'http://pbs.twimg.com/media/DTR0l3bWkAE5bXN.png',
        'media_url_https': 'https://pbs.twimg.com/media/DTR0l3bWkAE5bXN.png',
        'url': 'https://t.co/8QXLqcgJjz',
        'display_url': 'pic.twitter.com/8QXLqcgJjz',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951513694952927232/photo/1',
        'type': 'photo',
        'sizes': {
          'large': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'small': {'w': 680, 'h': 144, 'resize': 'fit'},
          'medium': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}
        }
      }]
  },
  'extended_entities': {
    'media': [
      {
        'id': 951513615164674000,
        'id_str': '951513615164674049',
        'indices': [40, 63],
        'media_url': 'http://pbs.twimg.com/media/DTR0l3bWkAE5bXN.png',
        'media_url_https': 'https://pbs.twimg.com/media/DTR0l3bWkAE5bXN.png',
        'url': 'https://t.co/8QXLqcgJjz',
        'display_url': 'pic.twitter.com/8QXLqcgJjz',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951513694952927232/photo/1',
        'type': 'photo',
        'sizes': {
          'large': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'small': {'w': 680, 'h': 144, 'resize': 'fit'},
          'medium': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}
        }
      }]
  },
  'favorited': false,
  'retweeted': false,
  'possibly_sensitive': false,
  'filter_level': 'low',
  'lang': 'en',
  'timestamp_ms': '1515693517803'
}

let imageOnly = {
  'created_at': 'Thu Jan 11 18:02:06 +0000 2018',
  'id': 951514570383941600,
  'id_str': '951514570383941636',
  'text': 'https://t.co/MzJzgXYqxD',
  'display_text_range': [0, 0],
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'truncated': false,
  'in_reply_to_status_id': null,
  'in_reply_to_status_id_str': null,
  'in_reply_to_user_id': null,
  'in_reply_to_user_id_str': null,
  'in_reply_to_screen_name': null,
  'user': {
    'id': 2616186000,
    'id_str': '2616186000',
    'name': 'Sojharo',
    'screen_name': 'SojharoMangi',
    'location': 'Hyderabad, Sindh',
    'url': null,
    'description': 'Enthusiastic about #WebRTC, #WebApp, #ECommerce, #ArtificialIntelligence, #MEAN, #Reading, #Writing, #Programming, #Philosophy http://lnkd.in/qCKxwr',
    'translator_type': 'none',
    'protected': false,
    'verified': false,
    'followers_count': 90,
    'friends_count': 98,
    'listed_count': 10,
    'favourites_count': 26,
    'statuses_count': 77,
    'created_at': 'Thu Jul 10 21:45:54 +0000 2014',
    'utc_offset': 18000,
    'time_zone': 'Asia/Karachi',
    'geo_enabled': false,
    'lang': 'en',
    'contributors_enabled': false,
    'is_translator': false,
    'profile_background_color': 'C0DEED',
    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_tile': false,
    'profile_link_color': '1DA1F2',
    'profile_sidebar_border_color': 'C0DEED',
    'profile_sidebar_fill_color': 'DDEEF6',
    'profile_text_color': '333333',
    'profile_use_background_image': true,
    'profile_image_url': 'http://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2616186000/1405029950',
    'default_profile': true,
    'default_profile_image': false,
    'following': null,
    'follow_request_sent': null,
    'notifications': null
  },
  'geo': null,
  'coordinates': null,
  'place': null,
  'contributors': null,
  'is_quote_status': false,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {
    'hashtags': [],
    'urls': [],
    'user_mentions': [],
    'symbols': [],
    'media': [
      {
        'id': 951514554835628000,
        'id_str': '951514554835628033',
        'indices': [0, 23],
        'media_url': 'http://pbs.twimg.com/media/DTR1cj-XcAEVGW-.png',
        'media_url_https': 'https://pbs.twimg.com/media/DTR1cj-XcAEVGW-.png',
        'url': 'https://t.co/MzJzgXYqxD',
        'display_url': 'pic.twitter.com/MzJzgXYqxD',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951514570383941636/photo/1',
        'type': 'photo',
        'sizes': {
          'large': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'small': {'w': 680, 'h': 144, 'resize': 'fit'},
          'medium': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}
        }
      }]
  },
  'extended_entities': {
    'media': [
      {
        'id': 951514554835628000,
        'id_str': '951514554835628033',
        'indices': [0, 23],
        'media_url': 'http://pbs.twimg.com/media/DTR1cj-XcAEVGW-.png',
        'media_url_https': 'https://pbs.twimg.com/media/DTR1cj-XcAEVGW-.png',
        'url': 'https://t.co/MzJzgXYqxD',
        'display_url': 'pic.twitter.com/MzJzgXYqxD',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951514570383941636/photo/1',
        'type': 'photo',
        'sizes': {
          'large': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'small': {'w': 680, 'h': 144, 'resize': 'fit'},
          'medium': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}
        }
      }]
  },
  'favorited': false,
  'retweeted': false,
  'possibly_sensitive': false,
  'filter_level': 'low',
  'lang': 'und',
  'timestamp_ms': '1515693726522'
}

let tweetMulitpleImages = {
  'created_at': 'Thu Jan 11 18:09:27 +0000 2018',
  'id': 951516420357148700,
  'id_str': '951516420357148672',
  'text': 'https://t.co/Vfw4M81XdQ',
  'display_text_range': [0, 0],
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'truncated': false,
  'in_reply_to_status_id': null,
  'in_reply_to_status_id_str': null,
  'in_reply_to_user_id': null,
  'in_reply_to_user_id_str': null,
  'in_reply_to_screen_name': null,
  'user': {
    'id': 2616186000,
    'id_str': '2616186000',
    'name': 'Sojharo',
    'screen_name': 'SojharoMangi',
    'location': 'Hyderabad, Sindh',
    'url': null,
    'description': 'Enthusiastic about #WebRTC, #WebApp, #ECommerce, #ArtificialIntelligence, #MEAN, #Reading, #Writing, #Programming, #Philosophy http://lnkd.in/qCKxwr',
    'translator_type': 'none',
    'protected': false,
    'verified': false,
    'followers_count': 90,
    'friends_count': 98,
    'listed_count': 10,
    'favourites_count': 26,
    'statuses_count': 77,
    'created_at': 'Thu Jul 10 21:45:54 +0000 2014',
    'utc_offset': 18000,
    'time_zone': 'Asia/Karachi',
    'geo_enabled': false,
    'lang': 'en',
    'contributors_enabled': false,
    'is_translator': false,
    'profile_background_color': 'C0DEED',
    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_tile': false,
    'profile_link_color': '1DA1F2',
    'profile_sidebar_border_color': 'C0DEED',
    'profile_sidebar_fill_color': 'DDEEF6',
    'profile_text_color': '333333',
    'profile_use_background_image': true,
    'profile_image_url': 'http://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2616186000/1405029950',
    'default_profile': true,
    'default_profile_image': false,
    'following': null,
    'follow_request_sent': null,
    'notifications': null
  },
  'geo': null,
  'coordinates': null,
  'place': null,
  'contributors': null,
  'is_quote_status': false,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {
    'hashtags': [],
    'urls': [],
    'user_mentions': [],
    'symbols': [],
    'media': [
      {
        'id': 951516356826075100,
        'id_str': '951516356826075136',
        'indices': [0, 23],
        'media_url': 'http://pbs.twimg.com/media/DTR3Fc6XkAAsLiM.png',
        'media_url_https': 'https://pbs.twimg.com/media/DTR3Fc6XkAAsLiM.png',
        'url': 'https://t.co/Vfw4M81XdQ',
        'display_url': 'pic.twitter.com/Vfw4M81XdQ',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951516420357148672/photo/1',
        'type': 'photo',
        'sizes': {
          'medium': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'large': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'small': {'w': 680, 'h': 144, 'resize': 'fit'},
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}
        }
      }]
  },
  'extended_entities': {
    'media': [
      {
        'id': 951516356826075100,
        'id_str': '951516356826075136',
        'indices': [0, 23],
        'media_url': 'http://pbs.twimg.com/media/DTR3Fc6XkAAsLiM.png',
        'media_url_https': 'https://pbs.twimg.com/media/DTR3Fc6XkAAsLiM.png',
        'url': 'https://t.co/Vfw4M81XdQ',
        'display_url': 'pic.twitter.com/Vfw4M81XdQ',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951516420357148672/photo/1',
        'type': 'photo',
        'sizes': {
          'medium': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'large': {'w': 1024, 'h': 217, 'resize': 'fit'},
          'small': {'w': 680, 'h': 144, 'resize': 'fit'},
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}
        }
      },
      {
        'id': 951516356985450500,
        'id_str': '951516356985450497',
        'indices': [0, 23],
        'media_url': 'http://pbs.twimg.com/media/DTR3FdgXcAEodIQ.jpg',
        'media_url_https': 'https://pbs.twimg.com/media/DTR3FdgXcAEodIQ.jpg',
        'url': 'https://t.co/Vfw4M81XdQ',
        'display_url': 'pic.twitter.com/Vfw4M81XdQ',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951516420357148672/photo/1',
        'type': 'photo',
        'sizes': {
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
          'medium': {'w': 1200, 'h': 786, 'resize': 'fit'},
          'large': {'w': 1366, 'h': 895, 'resize': 'fit'},
          'small': {'w': 680, 'h': 446, 'resize': 'fit'}
        }
      }]
  },
  'favorited': false,
  'retweeted': false,
  'possibly_sensitive': false,
  'filter_level': 'low',
  'lang': 'und',
  'timestamp_ms': '1515694167590'
}

let tweetVideo = {
  'created_at': 'Thu Jan 11 18:20:44 +0000 2018',
  'id': 951519261402517500,
  'id_str': '951519261402517504',
  'text': 'https://t.co/9o3OTR9dqD',
  'display_text_range': [0, 0],
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'truncated': false,
  'in_reply_to_status_id': null,
  'in_reply_to_status_id_str': null,
  'in_reply_to_user_id': null,
  'in_reply_to_user_id_str': null,
  'in_reply_to_screen_name': null,
  'user': {
    'id': 2616186000,
    'id_str': '2616186000',
    'name': 'Sojharo',
    'screen_name': 'SojharoMangi',
    'location': 'Hyderabad, Sindh',
    'url': null,
    'description': 'Enthusiastic about #WebRTC, #WebApp, #ECommerce, #ArtificialIntelligence, #MEAN, #Reading, #Writing, #Programming, #Philosophy http://lnkd.in/qCKxwr',
    'translator_type': 'none',
    'protected': false,
    'verified': false,
    'followers_count': 90,
    'friends_count': 98,
    'listed_count': 10,
    'favourites_count': 26,
    'statuses_count': 77,
    'created_at': 'Thu Jul 10 21:45:54 +0000 2014',
    'utc_offset': 18000,
    'time_zone': 'Asia/Karachi',
    'geo_enabled': false,
    'lang': 'en',
    'contributors_enabled': false,
    'is_translator': false,
    'profile_background_color': 'C0DEED',
    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
    'profile_background_tile': false,
    'profile_link_color': '1DA1F2',
    'profile_sidebar_border_color': 'C0DEED',
    'profile_sidebar_fill_color': 'DDEEF6',
    'profile_text_color': '333333',
    'profile_use_background_image': true,
    'profile_image_url': 'http://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/487354529726230528/ObT3TigA_normal.jpeg',
    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2616186000/1405029950',
    'default_profile': true,
    'default_profile_image': false,
    'following': null,
    'follow_request_sent': null,
    'notifications': null
  },
  'geo': null,
  'coordinates': null,
  'place': null,
  'contributors': null,
  'is_quote_status': false,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {
    'hashtags': [],
    'urls': [],
    'user_mentions': [],
    'symbols': [],
    'media': [
      {
        'id': 951519224819781600,
        'id_str': '951519224819781632',
        'indices': [0, 23],
        'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/951519224819781632/pu/img/0gVMlJxITDw8yNZd.jpg',
        'media_url_https': 'https://pbs.twimg.com/ext_tw_video_thumb/951519224819781632/pu/img/0gVMlJxITDw8yNZd.jpg',
        'url': 'https://t.co/9o3OTR9dqD',
        'display_url': 'pic.twitter.com/9o3OTR9dqD',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951519261402517504/video/1',
        'type': 'photo',
        'sizes': {
          'large': {'w': 560, 'h': 320, 'resize': 'fit'},
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
          'small': {'w': 560, 'h': 320, 'resize': 'fit'},
          'medium': {'w': 560, 'h': 320, 'resize': 'fit'}
        }
      }]
  },
  'extended_entities': {
    'media': [
      {
        'id': 951519224819781600,
        'id_str': '951519224819781632',
        'indices': [0, 23],
        'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/951519224819781632/pu/img/0gVMlJxITDw8yNZd.jpg',
        'media_url_https': 'https://pbs.twimg.com/ext_tw_video_thumb/951519224819781632/pu/img/0gVMlJxITDw8yNZd.jpg',
        'url': 'https://t.co/9o3OTR9dqD',
        'display_url': 'pic.twitter.com/9o3OTR9dqD',
        'expanded_url': 'https://twitter.com/SojharoMangi/status/951519261402517504/video/1',
        'type': 'video',
        'sizes': {
          'large': {'w': 560, 'h': 320, 'resize': 'fit'},
          'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
          'small': {'w': 560, 'h': 320, 'resize': 'fit'},
          'medium': {'w': 560, 'h': 320, 'resize': 'fit'}
        },
        'video_info': {
          'aspect_ratio': [7, 4],
          'duration_millis': 5533,
          'variants': [
            {
              'content_type': 'application/x-mpegURL',
              'url': 'https://video.twimg.com/ext_tw_video/951519224819781632/pu/pl/VzMh4JXeD3auy8UZ.m3u8'
            },
            {
              'bitrate': 320000,
              'content_type': 'video/mp4',
              'url': 'https://video.twimg.com/ext_tw_video/951519224819781632/pu/vid/314x180/CXhfy-jDnhtudRSk.mp4'
            }]
        }
      }]
  },
  'favorited': false,
  'retweeted': false,
  'possibly_sensitive': false,
  'filter_level': 'low',
  'lang': 'und',
  'timestamp_ms': '1515694844948'
}
